module.exports = {
  routes: [
    { method: 'GET', path: '/foundation/account', handler: 'foundation-hub.foundationAccount', config: { auth: { scope: [] } } },
    { method: 'POST', path: '/foundation/account', handler: 'foundation-hub.activateFoundationAccount', config: { auth: { scope: [] } } },
    { method: 'GET', path: '/foundation/profile/me', handler: 'foundation-hub.myProfile', config: { auth: { scope: [] } } },
    { method: 'PUT', path: '/foundation/profile', handler: 'foundation-hub.updateProfile', config: { auth: { scope: [] } } },
    { method: 'GET', path: '/foundation/impact', handler: 'foundation-hub.impactStats', config: { auth: false } },
    { method: 'GET', path: '/foundation/items', handler: 'foundation-hub.listItems', config: { auth: false } },
    { method: 'GET', path: '/foundation/items/:id', handler: 'foundation-hub.findItem', config: { auth: false } },
    { method: 'GET', path: '/foundation/me/items', handler: 'foundation-hub.myItems', config: { auth: { scope: [] } } },
    { method: 'POST', path: '/foundation/items', handler: 'foundation-hub.createItems', config: { auth: { scope: [] } } },
    { method: 'POST', path: '/foundation/items/:id/apply', handler: 'foundation-hub.applyForItem', config: { auth: { scope: [] } } },
    { method: 'GET', path: '/foundation/me/applications', handler: 'foundation-hub.myApplications', config: { auth: { scope: [] } } },
    { method: 'GET', path: '/foundation/me/requests', handler: 'foundation-hub.myRequests', config: { auth: { scope: [] } } },
    { method: 'GET', path: '/foundation/me/donation-history', handler: 'foundation-hub.donationHistory', config: { auth: { scope: [] } } },
    { method: 'PUT', path: '/foundation/applications/:id/review', handler: 'foundation-hub.reviewApplication', config: { auth: { scope: [] } } },
    { method: 'PUT', path: '/foundation/applications/:id/received', handler: 'foundation-hub.markReceived', config: { auth: { scope: [] } } },
    { method: 'GET', path: '/foundation/fundraisers', handler: 'foundation-hub.listFundraisers', config: { auth: false } },
    { method: 'GET', path: '/foundation/fundraisers/:id', handler: 'foundation-hub.findFundraiser', config: { auth: false } },
    { method: 'GET', path: '/foundation/me/fundraisers', handler: 'foundation-hub.myFundraisers', config: { auth: { scope: [] } } },
    { method: 'POST', path: '/foundation/fundraisers', handler: 'foundation-hub.createFundraiser', config: { auth: { scope: [] } } },
    { method: 'PUT', path: '/foundation/fundraisers/:id', handler: 'foundation-hub.updateFundraiser', config: { auth: { scope: [] } } },
    { method: 'POST', path: '/foundation/fundraisers/:id/pledge', handler: 'foundation-hub.pledgeFundraiser', config: { auth: { scope: [] } } },
    { method: 'POST', path: '/foundation/fundraisers/:id/comments', handler: 'foundation-hub.commentFundraiser', config: { auth: { scope: [] } } },
  ],
};
